### ISSUE TITLE
calculation of pi(π）with vcftools

### ISSUE THREAD

**Issue by vitty0513** [kchiou/kafue-baboons-ddrad#1]
Ihave a little question .If my vcf fille contains 2 strains,drug-resistant and wlid type,and 3 repeat for each strain.Can i calculate the pi directly,or some other way to deal with my  strain before calculation?Any help will be greatly appreciated!

**Comment by kchiou** [comment]
You could calculate pi both directly, and split by strain. To do the latter, just run vcftools with the `--keep` argument and a file containing a list of your biological replicates.

**Comment by vitty0513** [comment]
If i calculate pi directly with the 6 samples（2 strains）,can  the results ,the pi value ,explain the nucleotide diversity between the 2 strain？

**Comment by kchiou** [comment]
Gotcha. No, the calculation of pi in VCFtools does not give nucleotide diversity _between_. To my knowledge, VCFtools does not output the statistic you want, but it does calculate it as part of Fst.

Weir & Cockerham's Fst is calculated as (pi_between - pi_within) / pi_between. That means that, to output the statistic you want, you simply need to modify the source code so that the denominator is added to the output. Basically, you would make the changes here: https://github.com/kchiou/vcftools/commit/20fc6c2

I haven't tested the code yet, but it should work. If you make those changes to the source code and recompile the modified program, you should be able to obtain pi_between on sites or windows using the `--weir-fst-pop` argument.

**Comment by vitty0513** [comment]
thank you so much
